name: Create Issue on File Addition

on:
  push:
    branches:
      - main

jobs:
  create-issue:
    runs-on: ubuntu-latest

    steps:
      - name: Check for Added Files
        id: check-files
        run: echo "::set-output name=files::$(git diff --name-only ${{ github.sha }} ${{ github.event.before }})"

      - name: Create Issue
        uses: actions/github-script@4.3.0
        with:
          script: |
            const github = context.github;
            const { owner, repo } = context.repo;

            const addedFiles = ${{ steps.check-files.outputs.files }};
            
            if (addedFiles.length > 0) {
              const issueTitle = 'New Files Added';
              const issueBody = `The following files were added:\n\n${addedFiles.join('\n')}`;

              await github.issues.create({
                owner,
                repo,
                title: issueTitle,
                body: issueBody
              });
            } else {
              console.log('No new files added. Skipping issue creation.');
            }
